### ISSUE TITLE
How can I test CLaTr in the wild?

### ISSUE THREAD

**Issue by heheyas** [robincourant/CLaTr#1]
Hi, 

Congrats to your great work on E.T. The proposed CLaTr is inspiring. I wonder how to use CLaTr in the wild, i.e. calculating similarity given a camera path and its textual description. The current code seems only to contain testing with pre-computed text features. Which text encoder does CLaTr use and could you provide a little code snippet on encoding the text? Thanks in advance.

Best regards,
heheyas

**Comment by robincourant** [comment]
Hi, 

Thanks for your interest in our work!

Indeed, this CLaTr repository is a bit rough and lacks context. 
We use CLIP-ViT-B/32 from the [OpenAI repo](https://github.com/openai/CLIP).
You can find the [extraction code](https://github.com/robincourant/the-exceptional-trajectories/blob/main/scripts/misc/clip_extraction.py) in our other repository. 

Additionally, please be mindful of the trajectory feature processing, especially the velocity processing and normalization (refer to [this](https://github.com/robincourant/CLaTr/blob/main/src/datasets/modalities/trajectory_dataset.py) and [this](https://github.com/robincourant/CLaTr/blob/main/configs/dataset/standardization/0300.yaml)).

**Comment by heheyas** [comment]
Thank you so much for your reply. Besides, is it better to normalize the camera path before performing the velocity processing and normalization? (e.g. normalize the camera path into a unit bbox)

**Comment by robincourant** [comment]
We first compute the velocity from the raw trajectory translation that we append with its origin translation. Then, we normalize both the origin (with `shift_mean` and `shift_std`) and the velocity (with `norm_mean` and `norm_std`). 
For the rotation, we only convert them to the 6d-continuous representation.
I hope this answers your question.

**Comment by heheyas** [comment]
Yes, thank you so much for your help!
